# Gemfile for Jekyll docs (e.g. GitHub Actions).
# The theme is published as the "minima" gem, not "jekyll-theme-minima".
source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "minima", "~> 2.5"
gem "webrick", "~> 1.7"
